### ISSUE TITLE
About the experimental code

### ISSUE THREAD

**Issue by lnzz21** [leeh2213/MB2C#1]
I'm very interested in your experiment and would like to get the code for it

**Comment by leeh2213** [comment]
Thank you for your interest in this research! I’m glad to hear you’re excited about the work.
I will be releasing the full code and model weights soon, and I appreciate your patience while I prepare everything for public access. Please stay tuned for an update, and I’ll provide the links as soon as they’re available. In the meantime, if you have any specific questions or need additional details, feel free to ask! 😊

**Comment by leeh2213** [comment]
Thank you for your patience and interest in our work! 😊 I’m happy to share that I’ve now uploaded the full code to the repository. You can find it in the main branch.

Feel free to explore the code, and if you have any questions or need further assistance, don’t hesitate to ask. I’d love to hear your thoughts or feedback on the project!

Best regards,
